# -----------------------------------------
# Namespace
# -----------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: ttt-game-system
--- 
# -----------------------------------------
# Deployment
# ----------------------------------------- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-api-gateway-deployment
  labels:
    app: ttt-api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ttt-api-gateway
  template:
    metadata:
      labels:
        app: ttt-api-gateway
    spec:
      containers:
      - name:  api-gateway
        image: ttt-api-gateway
        ports:
        - containerPort: 8080
